#!/bin/bash

#echo -n  "Do You Want to Update Your System ? "

#read STRING

#if [[ "$STRING" == "yes" || "$STRING" == "y" ]]
#then
 # sudo dnf update -y

#echo  "Your System has been Updated "

#fi

echo -n "Do You Want to Enable RPMFusion repo ? "

read STRING1

if [[ "$STRING1" == "yes" ]]
then
  sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

echo "RPMFusion repo is Now Enabled "

fi

echo -n "Do You Want To Install The Metadata And Multimedia From RPMFuison ? "

read STRING2

if [[ "$STRING2" == "yes" || "$STRING2" == "y" ]]
then
  sudo dnf groupupdate core -y

  sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y

  sudo dnf groupupdate sound-and-video -y
 
  sudo dnf install rpmfusion-free-release-tainted -y

  sudo dnf install libdvdcss  -y

  sudo dnf install rpmfusion-nonfree-release-tainted -y

  sudo dnf install \*-firmware -y

fi

echo -n "Do You Want To Instal The NVIDIA Driver ? "

read STRING3

if [[ "$STRING3" == "yes" || "$STRING3" == "y" ]]
then 
  sudo dnf update -y

  sudo dnf install akmod-nvidia -y

  sudo dnf install xorg-x11-drv-nvidia-cuda -y

  sudo dnf install vulkan -y

  sudo dnf install xorg-x11-drv-nvidia-cuda-libs -y

fi

echo -n "Do You Want To Install WINE-STAGING for GAMING ? "

read STRING4

if [[ "$STRING4" == "yes" || "$STRING4" == "y" ]]
then
  sudo dnf config-manager --add-repo https://dl.winehq.org/wine-builds/fedora/35/winehq.repo

  sudo dnf install winehq-staging -y

fi

echo -n "Do You Want To Install STEAM and LUTRIS for GAMING ? " 

read STRING5

if [[ "$STRING5" == "yes" || "$STRING5" == "y" ]]
then

  sudo dnf install steam lutris  -y

fi

echo -n "Do You Want To Enable And USE FLATPAKs ? "

read STRING6

if [[ "$STRING6" == "yes" || "$STRING6" == "y" ]]
then

  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

fi

echo -n "Do You Want To Install  The GNOME Tweaks and Extensions Tools ? " 

read STRING7

if [[ "$STRING7" == "yes" || "$STRING7" == "y" ]]
then

  sudo dnf install gnome-extensions-app gnome-tweaks -y

fi

echo "You Are Ready And Fully LOADED :) ! "







